### ISSUE TITLE
New authorization mechanism is not supported

### ISSUE THREAD

**Issue by kek** [erlcloud/erlcloud#154]
When trying to operate on a bucket located in Frankfurt, it fails with the error message "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.". 

```
10> erlcloud_s3:get_bucket_policy("[bucket name]").
{error,{http_error,400,"Bad Request",
                   <<"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidRequest</Code><Message>The author"...>>}}
```

According to Amazon, new regions need to use this different authentication mechanism: http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

A similar issue here: http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4

**Comment by teodor-pripoae** [comment]
Is there any plan to introduce V4 signature support for S3 ?

**Comment by ransomr** [comment]
@redeye-it contacted me a couple of weeks ago about making this change for EC2 and AS but I haven't heard anything since then so don't know if he is actively working on it. V4 signatures are already implemented and used by DynamoDB, so the change to use them from `erlcloud_aws:aws_request2_no_update` shouldn't be too hard and should fix most services. I welcome a PR with this change.

**Comment by werbitzky** [comment]
+1

**Comment by motobob** [comment]
@wagerlabs @ransomr i'm nearly finished with SigV4 across the board in https://github.com/alertlogic/erlcloud/pull/5 and that will get populated to upstream asap after

**Comment by drobakowski** [comment]
@motobob thanks for your work on this! Do you have any news on this or maybe even a rough estimation when your changes are ready for upstream?

**Comment by motobob** [comment]
@drobakowski this is done in our fork. I'll get to merging this to upstream asap. unfortunately our fork went quite away ahead and i need to fix it too.

**Comment by ulrobix** [comment]
Please fix it

**Comment by motobob** [comment]
i thought we already merged SigV4 support here

**Comment by ulrobix** [comment]
Thanks for fast reply, but I still get the error when using s3.eu-central-1.amazonaws.com

**Comment by motobob** [comment]
sorry... it looks like the S3 portion of this was not merged in #218... @lilrooness is there anyway for you resume this merging effort? 

@ulrobix in the meantime you try using our [fork](https://github.com/alertlogic/erlcloud). I know it's not the best practice but can help you.

**Comment by waisbrot** [comment]
The AlertLogic fork has been merged in, including code for this.
